### ISSUE TITLE
06.07 모누티 개발일지

### ISSUE THREAD

**Issue by MartinLeeSJ** [MartinLeeSJ/GongdeunTop#48]
# TODO
TargetList 손보기
- [x] TargetListCell 이 너무 큰 느낌이 있다. => TargetListCell 을 DisclosureGroup으로 바꿔서 하단 가로 스크롤 부분을 content로 이동시키기  
- [x] TargetListCell 우측상단 타깃의 기간을 단기 중기 중장기 장기로 보여주는 라벨이 직관적이지 못하다 => 게이지로 바꿔서 직관적이게 만들기
- [x] SetTargetForm Localization 완성하기
- [x] SetTargetForm 제목 추가해서 현재 시트가 타깃을 추가하는 시트라는 것을 명확하게 만들기
- [x] SetTargetFrom presentationDetent를 하나더 추가해서 넓게 보고 싶은 사람들의 니즈 충족하기

# Result
