### ISSUE TITLE
06.12 모누티 개발일지

### ISSUE THREAD

**Issue by MartinLeeSJ** [MartinLeeSJ/GongdeunTop#59]
# TODO
- [x] Target Multiple Remove 구현
- [ ] Target Detail 뷰 구현
- [ ] Target Edit 기능 구현
- [x] Todo - Target 연결

**Comment by MartinLeeSJ** [comment]
- Target DetailView, Target Edit 기능은 익일 To Do로 이동
