### ISSUE TITLE
06.13 - 14 모누티 개발일지

### ISSUE THREAD

**Issue by MartinLeeSJ** [MartinLeeSJ/GongdeunTop#61]
# TODO 
- Target
    - [ ] #63
    - [ ] Target Edit Feature
    - [ ] Todo Multiple Deletion 기능 동작시 Target에서 해당 To Do 제거
- Set To Do Form
    - [ ] FormContainer Footer UI 수정
- Calendar뷰
    - [ ] UI 색상 조정
