### ISSUE TITLE
07.21 모누티 개발일지

### ISSUE THREAD

**Issue by MartinLeeSJ** [MartinLeeSJ/GongdeunTop#79]
# TODO
- [x] 시간 개별 설정모드에서 세션을 무한대로 추가할 수 있는 버그 수정
- [x] 시간 개별 설정모드에서 일괄 설정 모드로 넘어올 때 세션이 일괄설정 모드에서 정할 수 있는 한계를 넘기면 잠기는 오류 해결
    - 일괄 재설정 버튼을 도입할 건지, 세션 개수를 한계치 이내로 되돌리는 버튼을 도입할 건지 결정
- [ ] ~~시간 개별 설정모드 UI 변경하기~~
- [x] 시간 개별 설정모드 초단위 설정 5배수로 고치기
