### ISSUE TITLE
07.23 모누티개발일지

### ISSUE THREAD

**Issue by MartinLeeSJ** [MartinLeeSJ/GongdeunTop#82]
# TODO
버전 0.9.1을 출시하기위해 자잘한 버그 수정하기
- [x] 투두리스트 시간 오름내림차순 버그 해결
- [x] 새 투두 추가할 때 목표를 목록에서 선택할 수 있게 바꾸기
- [x] 새 투두 추가할 때 시트가 자동으로 내려가서 추가가 되었다는 것을 사용자가 알 수 있게 하기
- [x] 새 투두 추가하는 부분 키보드 툴바 버튼 한 쪽으로 몰기
- [ ] 버전 0.9.1 테스트플라이트 출시
