### ISSUE TITLE
07.26 모누티 개발일지

### ISSUE THREAD

**Issue by MartinLeeSJ** [MartinLeeSJ/GongdeunTop#89]
# TODO
- [x] 타겟 디테일뷰가 보이지 않는 문제 해결
- [ ] 타겟의 항목중에 완료된 할일 부분 수정
    - 현재 완료한 할일, 완료하지 않은 할일 모두 같이 집계되어 나와있다
- [ ] 타겟의 항목중에 성취도 부분 수정
- [ ] 특정 타겟이 삭제되지 않는 문제 해결
- [ ] V0.9.2 출시

**Comment by MartinLeeSJ** [comment]
- 타겟의 항목중에서 완료된 할 일과 성취도 부분은 ToDoStore, ToDoManager 의 리팩토링이 선행되어야한다.
