### ISSUE TITLE
07.31 모누티 개발일지

### ISSUE THREAD

**Issue by MartinLeeSJ** [MartinLeeSJ/GongdeunTop#98]
# TODO
- [x] 캘린더뷰에 처음 진입할 때 버벅임 제거하기
  - 데이터 불러오기 로직 개선
  - CycleRepository 만들기
  - CycleManager 개선
- [x] 사용자의 설정에 따라 일요일을 한주에 첫번째로 하는지 결정하는 기능
- [x] 월 선택 팝업 색 테마에 맞게 조정
- [x] 달력 UI 간격조정
